WITH Gen1 AS (
    SELECT ID AS Gen1_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
Gen2 AS (
    SELECT e.ID AS Gen2_ID, e.PARENT_ID
    FROM ECOLI_DATA e
    JOIN Gen1 g1 ON e.PARENT_ID = g1.Gen1_ID
),
Gen3 AS (
    SELECT e.ID AS Gen3_ID, e.PARENT_ID
    FROM ECOLI_DATA e
    JOIN Gen2 g2 ON e.PARENT_ID = g2.Gen2_ID
)
SELECT Gen3_ID AS ID
FROM Gen3
ORDER BY ID;
