-- 코드를 입력하세요
WITH MAX_VIEWS_BOARD AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
)
SELECT 
    CONCAT('/home/grep/src/', UF.BOARD_ID, '/', UF.FILE_ID, UF.FILE_NAME, UF.FILE_EXT) AS FILE_PATH
FROM 
    USED_GOODS_FILE UF
JOIN 
    MAX_VIEWS_BOARD MB
ON 
    UF.BOARD_ID = MB.BOARD_ID
ORDER BY 
    UF.FILE_ID DESC;
